export const MICROSERVICES = {
  USERS_SERVICE: "USERS_SERVICE",
  PRODUCTS_SERVICE: "PRODUCTS_SERVICE",
  SHOPPING_CART_SERVICE: "SHOPPING_CART_SERVICE",
  ORDER_SERVICE: "ORDER_SERVICE",
  PAYMENT_SERVICE: "PAYMENT_SERVICE",
} as const;
